export const Types = {
  ADD_USER: "ADD_USER",
  CURRENT_USER: "CURRENT_USER",
  LOG_OUT: "LOG_OUT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS",
  ITEM_INCREMENT: "ITEM_INCREMENT",
  ITEM_DECREMENT: "ITEM_DECREMENT",
  LOAD_PRODUCT: "LOAD_PRODUCT",
  PLACE_ORDER: "PLACE_ORDER",
  COMPLETE_ORDER: "COMPLETE_ORDER",
};
